routes/web.php
<?php

Route::redirect('/', '/page');

Auth::routes(['register' => false]);
Route::get('/login/admin', 'Auth\LoginController@showAdminLoginForm');
Route::post('/login/admin', 'Auth\LoginController@adminLogin')->name('admin.login.post');

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth:admin']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::delete('permissions/destroy', 'PermissionsController@massDestroy')->name('permissions.massDestroy');
    Route::resource('permissions', 'PermissionsController');
    Route::delete('roles/destroy', 'RolesController@massDestroy')->name('roles.massDestroy');
    Route::resource('roles', 'RolesController');
    Route::delete('users/destroy', 'UsersController@massDestroy')->name('users.massDestroy');
    Route::resource('users', 'UsersController');
    Route::delete('products/destroy', 'ProductsController@massDestroy')->name('products.massDestroy');
    Route::resource('products', 'ProductsController');
    Route::get('settings/index','ConfigController@index')->name('settings.index');
    Route::put('settings/update/{config_id}','ConfigController@update')->name('settings.update');
});

Route::group(['prefix' => 'page','as'=>'page.','namespace' => 'Frontend'], function () {
    Route::redirect('/', 'page/landing');
    Route::get('landing','HomeController@index')->name('landing');
    Route::get('/login/customers', 'LoginController@showLoginForm')->name('customer.login');
    Route::post('/login/customers', 'LoginController@customerLogin')->name('customer.login.post');

    Route::get('/register/customer', 'RegisterController@showRegistrationForm')->name('customer.register');
    Route::post('/register/customer', 'RegisterController@register')->name('customer.register.post');

    Route::get('profile/account/{user_id}','ProfileController@index')->name('profile.index');
    Route::put('profile/update/{user_id}','ProfileController@update')->name('profile.update');
    Route::post('profile/update/password','ProfileController@updatePassword')->name('profile.update.password');
    Route::post('profile/updateCustomerType','ProfileController@updateCustomerType')->name('profile.update.type');

    Route::get('profile/travels/reserved','ProfileController@travelsReserved')->name('profile.travels.reserved');
    Route::get('profile/travels/created','ProfileController@travelsCreated')->name('profile.travels.created');
    Route::get('profile/travels/created/edit/{travel_id}','ProfileController@travelsCreatedEdit')->name('profile.travels.created.edit');
    Route::put('profile/travels/created/update/{travel_id}','ProfileController@travelsCreatedUpdate')->name('profile.travels.created.update');
    Route::get('profile/reviews','ProfileController@reviews')->name('profile.reviews');
    Route::get('profile/notifications','ProfileController@notifications')->name('profile.notifications');

    Route::get('profile/cars/', 'ProfileController@carsIndex')->name('profile.cars.index');
    Route::get('profile/cars/edit', 'ProfileController@carsEdit')->name('profile.cars.edit');
    Route::put('profile/cars/update/{card_id}', 'ProfileController@carsUpdate')->name('profile.cars.update');
    Route::get('profile/cars/create', 'ProfileController@carsCreate')->name('profile.cars.create');
    Route::post('profile/cars/store', 'ProfileController@carsStore')->name('profile.cars.store');

    Route::get('profile/payments','ProfileController@payments')->name('profile.payments');
    Route::get('travel/find/','TravelController@find')->name('travel.find');
    Route::get('travel/find/search','TravelController@findSearch')->name('travel.find.search');
    Route::get('travel/details/{travel_id}','TravelController@details')->name('travel.details');
    Route::get('travel/reserve/{path_id}','TravelController@reserveTravel')->name('travel.reserve');

    Route::get('travel/create/','TravelController@create')->name('travel.create');
    Route::post('travel/create/store','TravelController@createTravel')->name('travel.store');

});

app/Http/Controllers/Frontend/CustomersController.php
<?php


namespace App\Http\Controllers\Frontend;


use App\Http\Requests\StoreCustomerRequest;
use App\Http\Requests\UpdateCustomerRequest;
use App\Repositories\CustomersAddresRepository;
use App\Repositories\CustomersRepository;
use Illuminate\Auth\Events\Registered;
use Illuminate\Http\Request;
use Illuminate\Routing\Controller;
use Validator;
use Auth, Log;

class CustomersController extends Controller
{

    protected $customer;

    protected $customerRepository;

    protected $customerAddressRepository;

    public function __construct(CustomersRepository $customerRepository, CustomersAddresRepository $customerAddressRepository)
    {
        $this->customerRepository = $customerRepository;
        $this->customerAddressRepository = $customerAddressRepository;
        $this->middleware('auth:customer');
    }

    public function profile($customer_id)
    {

        $customer = $this->customerRepository->find($customer_id);
        return view('frontend.customers.account.profile', compact('customer'));
    }

    public function profileUpdate(UpdateCustomerRequest $request, $customer_id)
    {
        if ($request->has('password'))
        {
            $request->password = \Hash::make($request->password);
        }
        $this->customerRepository->update($request->all(),$customer_id);
        toastSuccess('Pefil actualizado','Actualizado');
        return redirect()->back();
    }

    public function orders($customer_id)
    {
        $customer = $this->customerRepository->find($customer_id);
        return view('frontend.customers.account.orders',compact('customer'));
    }

    public function wishlist($customer_id)
    {
        $customer = $this->customerRepository->find($customer_id);
        return view('frontend.customers.account.wishlist',compact('customer'));
    }

    public function address($customer_id)
    {
        $customer = $this->customerRepository->find($customer_id);
        return view('frontend.customers.account.address.index',compact('customer'));
    }

    public function addressEdit($address_id)
    {
        $address = $this->customerAddressRepository->find($address_id);
        return view('frontend.customers.account.address.edit',compact('address'));
    }

    public function addressUpdate(Request $request,$address_id)
    {
        $this->customerAddressRepository->update($request->all(),$address_id);
        toastr()->success('Direccion actualizada correctamente','OK!!');
        return redirect()->back();
    }

    public function addressAdd($customer_id)
    {
        $customer = $this->customerRepository->find($customer_id);
        return view('frontend.customers.account.address.add',compact('customer'));
    }

    public function addressStore(Request $request)
    {
        $this->customer = auth()->guard('customer')->user();
        $requestData = null;
        if ($request->has('default_address'))
        {
            $requestData = $request->all();
            $requestData['default_address'] = true;

            if ($this->customer->addresses->count() >= 1) {
                foreach ($this->customer->addresses as $address){
                    $data['default_address'] = false;
                    $this->customerAddressRepository->update($data,$address->id);
                }
            }
        }

        $this->customerAddressRepository->create($requestData);
        toastr()->success('Direccion agregada', 'OK!!');
        return redirect()->route('page.customer.address',$request->customer_id);
    }

    public function addressDelete($address_id)
    {
        $this->customerAddressRepository->delete($address_id);
        toastr()->success('Direccion eliminada correctamente','Eliminado');
        return redirect()->back();
    }

}

app/Http/Controllers/Frontend/HomeController.php
<?php


namespace App\Http\Controllers\Frontend;


use App\Http\Controllers\Controller;
use App\Repositories\CategoriesRepository;
use Illuminate\Contracts\Support\Renderable;
use Auth, Cart;

class HomeController extends Controller
{
    /**
     * Show the application dashboard.
     *
     * @return Renderable
     */
    public function index()
    {
        return view('frontend.landing.index');
    }
}

app/Http/Controllers/Frontend/LoginController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Http\Controllers\Controller;
use Illuminate\Foundation\Auth\AuthenticatesUsers;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Auth;
use Illuminate\Contracts\Auth\StatefulGuard;
use Illuminate\Contracts\View\View;
use Cart;

class LoginController extends Controller
{
    /*
    |--------------------------------------------------------------------------
    | Login Controller
    |--------------------------------------------------------------------------
    |
    | This controller handles authenticating users for the application and
    | redirecting them to your home screen. The controller uses a trait
    | to conveniently provide its functionality to your applications.
    |
    */

    use AuthenticatesUsers;

    /**
     * Where to redirect users after login.
     *
     * @var string
     */
    protected $redirectTo = '/page';

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('guest')->except('logout');
        //$this->middleware('guest:customer')->except('logout');
    }

    /**
     * Send the response after the user was authenticated.
     *
     * @param  Request  $request
     * @return Response
     */
    protected function sendLoginResponse(Request $request)
    {
        $request->session()->regenerate();

        $this->clearLoginAttempts($request);

        return $this->authenticated($request, $this->guard()->user())
            ?: redirect()->intended($this->redirectPath());
    }


    /**
     * Show the application's login form.
     *
     * @return View
     */
    public function showLoginForm()
    {
        return view('auth.login_customers');
    }

    public function customerLogin(Request $request)
    {
        $validator = $this->validate($request, [
            'email'   => 'required|email',
            'password' => 'required|min:6'
        ]);


        if ($this->guard()->attempt(['email' => $request->email, 'password' => $request->password], $request->get('remember'))) {

            toastSuccess('Bienvenido de nuevo','OK!!');
            toastr()->success('Bienvenido de nuevo','Ok!!');
            return redirect()->intended('/page/landing');
        }

        return back()->withInput($request->only('email', 'remember'));
    }



//    /**
//     * Get the guard to be used during authentication.
//     *
//     * @return StatefulGuard
//     */
//    protected function guard()
//    {
//        return Auth::guard('customer');
//    }
}

app/Http/Controllers/Frontend/RegisterController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Models\User;
use App\Http\Controllers\Controller;
use Carbon\Carbon;
use Hash, Validator,Auth;
use Illuminate\Auth\Events\Registered;
use Illuminate\Contracts\Auth\StatefulGuard;
use Illuminate\Foundation\Auth\RegistersUsers;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Response;


class RegisterController extends Controller
{
    /*
    |--------------------------------------------------------------------------
    | Register Controller
    |--------------------------------------------------------------------------
    |
    | This controller handles the registration of new users as well as their
    | validation and creation. By default this controller uses a trait to
    | provide this functionality without requiring any additional code.
    |
    */

    use RegistersUsers;

    /**
     * Where to redirect users after registration.
     *
     * @var string
     */
    protected $redirectTo = '/page/landing';

    /**
     * Create a new controller instance.
     *
     *
     */
    public function __construct()
    {
        $this->middleware('guest');
    }

    /**
     * Get a validator for an incoming registration request.
     *
     * @param  array  $data
     * @return \Illuminate\Contracts\Validation\Validator
     */
    protected function validator(array $data)
    {
        return Validator::make($data, [
            'firstname' => 'required|string|max:255',
            'lastname' => 'required|string|max:255',
            'email' => 'required|string|email|max:255|unique:users',
            'password' => 'required|string|confirmed',
        ],[ 'first_name.required'=> 'El nombre es requerido',
            'last_name.required'=> 'El apellido es requerido',
            'email.unique'=> 'El email existe, favor cambiarlo',
            'password.required' => 'Contraseña es requerido',
        ]);
    }


    /**
     * Create a new user instance after a valid registration.
     *
     * @param  array  $data
     * @return User
     */
    protected function create(array $data)
    {
        return User::create([
            'firstname' => $data['firstname'],
            'lastname' => $data['lastname'],
            'phone' => $data['phone'],
            //'address' => $data['address'],
            'type' => $data['type'],
            'sex' => $data['sex'],
            'email' => $data['email'],
            'date_birth' =>$data['date_birth_submit'],
            'password' => Hash::make($data['password']),
        ]);
    }


    /**
     * Handle a registration request for the application.
     *
     * @param  Request  $request
     * @return Response | RedirectResponse
     */
    public function register(Request $request)
    {
        //dd($request->all());
        $this->validator($request->all())->validate();

        event(new Registered($user = $this->create($request->all())));

        $this->guard()->login($user);

        toastr()->success('Registro completado satisfactoriamente','OK!');

        return $this->registered($request, $user)
            ?: redirect($this->redirectPath());
    }
}

resources/views/layouts/frontend/footer.blade.php
<!-- Footer -->
<footer class="footer bg-light">
    <div class="container text-center">
        <img  href="index.html" src="{{ asset('img/logo.png') }}" alt="logo">

    </div>
    <div class="container">
        <div class="row">
            <div class="col-lg-6 h-100 text-center text-lg-left my-auto">
                <p class="text-muted small mb-4 mb-lg-0">&copy; Comparti2. Todos los derechos reservados</p>
            </div>
            <div class="col-lg-6 h-100 text-center text-lg-right my-auto">
                <p class="text-muted small mb-4 mb-lg-0">Power by @NANO Deverloper</p>
            </div>
        </div>
    </div>
</footer>

resources/views/layouts/frontend/header.blade.php
<!-- Navigation -->
<div class="container mb-2 mt-2 ">
    <nav class="navbar navbar-expand-lg navbar-light text-center" >
        <a title="logo" href="{{ route('page.landing') }}">
            <img  class="navbar-brand" src="{{ asset('img/logo.png') }}" alt="logo">
        </a>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav ml-auto text-center">
                @guest()
                <a class="nav-item nav-link text-success2" href="{{ route('page.travel.create') }}"><i class="fas fa-plus-circle"></i>
                    Publicar Viaje <span class="sr-only">(menu)</span></a>
                <a class="nav-item nav-link text-success2" href="{{ route('page.travel.find') }}"> <i class="fas fa-search"></i> Buscar Viaje</a>
                <a class="nav-item nav-link text-success" href="{{ route('page.customer.login') }}">Iniciar Sesión</a>
                <a class="btn btn-success2 borderder borderiz " href="{{ route('page.customer.register') }}"> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Registro&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</a>
                @endguest

                @if(Auth::check())

                   @if(Auth::user()->type == 'passenger')
                        <a class="nav-item nav-link" href="{{ route('page.travel.find') }} ">Buscar viaje</a>
                   @else
                        <!-- Alertas de notificaciones -->
                            <li class="nav-item dropdown no-arrow mx-1">
                                <a class="nav-link dropdown-toggle" href="#" id="alertsDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <i class="fas fa-bell fa-fw"></i>
                                    <!-- Counter - Alerts -->
                                    <span class="badge badge-danger badge-counter">3+</span>
                                </a>
                                <!-- Dropdown - Alerts -->
                                <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="alertsDropdown">
                                    <h6 class="dropdown-header">
                                        Centro de notificaciones
                                    </h6>
                                    <a class="dropdown-item d-flex align-items-center" href="#">
                                        <div class="mr-3">
                                            <div class="icon-circle bg-primary">
                                                <i class="fas fa-file-alt text-white"></i>
                                            </div>
                                        </div>
                                        <div>
                                            <div class="small text-gray-500">{{ \Carbon\Carbon::now()->calendar() }}</div>
                                            Su viaje a Encarnacion del dia Viernes 25 de Febrero fue reservado por 1 pasajero
                                        </div>
                                    </a>
                                    <a class="dropdown-item d-flex align-items-center" href="#">
                                        <div class="mr-3">
                                            <div class="icon-circle bg-success">
                                                <i class="fas fa-donate text-white"></i>
                                            </div>
                                        </div>
                                        <div>
                                            <div class="small text-gray-500">{{ \Carbon\Carbon::now()->calendar() }}</div>
                                            Su viaje a Encarnacion del dia Viernes 25 de Febrero fue reservado por 1 pasajero
                                        </div>
                                    </a>
                                    <a class="dropdown-item d-flex align-items-center" href="#">
                                        <div class="mr-3">
                                            <div class="icon-circle bg-warning">
                                                <i class="fas fa-exclamation-triangle text-white"></i>
                                            </div>
                                        </div>
                                        <div>
                                            <div class="small text-gray-500">{{ \Carbon\Carbon::now()->sub('8 days')->calendar() }}</div>
                                            Se ha acredito a tu cuenta GS. 320.000
                                        </div>
                                    </a>
                                    <a class="dropdown-item text-center small text-gray-500" href="#">Mostrar todas las alertas</a>
                                </div>
                            </li>
                            <a class="nav-item nav-link" href="{{ route('page.travel.create')}}">Publicar viaje</a>
                   @endif
                    <li class="dropdown user nav-item nav-link">
                    <a class="dropdown-toggle text-success" data-toggle="dropdown" href="#">
                        <i class="icon-user text-success"></i>
                        {{ Auth::user()->fullName }}
                    </a>
                    <ul class="dropdown-menu">

                        <li class="ml-2">
                            <i class="fas fa-cog"></i>
                            <a href="{{ route('page.profile.index',[Auth::user()->id]) }}">
                                <font style="vertical-align: inherit;">
                                    <font class="text-gray1" style="vertical-align: inherit;">Mi perfil</font>
                                </font>
                            </a>
                        </li>
                        <li class="ml-2">
                            <i class="fas fa-list-alt"></i>
                            <a href="{{ route('page.profile.index',[Auth::user()->id]) }}"><font style="vertical-align: inherit;"><font class="text-gray1" style="vertical-align: inherit;">Historial</font></font></a>
                        </li>
                        <li class="divider"></li>
                        <li class="ml-2">
                            <i class="fas fa-arrow-alt-circle-left"></i>
                            <a href="#" onclick="event.preventDefault(); document.getElementById('logoutform').submit();">
                                <font style="vertical-align: inherit;">
                                    <font class="text-gray1" style="vertical-align: inherit;">
                                        Cerrar Sesión
                                    </font>
                                </font>
                            </a>
                        </li>
                    </ul>
                    </li>

                @endif
            </div>
        </div>
    </nav>
</div>

resources/views/layouts/frontend/master.blade.php
<!DOCTYPE html>
<html lang="es">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <meta name="appUrl" content="{{ url('page') }}">
    <meta name="precio_pasaje" content="{{ $precio_viaje }}">

    <meta name="description" content="Comparti2 - Otra manera de viajer y ahorrar dinero">
    <meta name="keywords" content="cars, share, travel, customers, money, two">
    <meta name="author" content="Nano developers">

    <!-- Favicon and Touch Icons-->
    <link rel="apple-touch-icon" sizes="60x60" href="{{ asset('images/icons/apple-icon-60x60.png') }}">
    <link rel="apple-touch-icon" sizes="72x72" href="{{ asset('images/icons/apple-icon-72x72.png') }}">
    <link rel="apple-touch-icon" sizes="76x76" href="{{ asset('images/icons/apple-icon-76x76.png') }}">
    <link rel="apple-touch-icon" sizes="120x120" href="{{ asset('images/icons/apple-icon-120x120.png') }}">
    <link rel="apple-touch-icon" sizes="152x152" href="{{ asset('images/icons/apple-icon-152x152.png') }}">
    <link rel="apple-touch-icon" sizes="180x180" href="{{ asset('images/icons/apple-icon-180x180.png') }}">
    <link rel="icon" type="image/png" sizes="32x32" href="{{ asset('images/icons/favicon-32x32.png') }}">
    <link rel="icon" type="image/png" sizes="16x16" href="{{ asset('images/icons/favicon-16x16.png') }}">


    <!-- Web Application Manifest -->
    <link rel="manifest" href="{{ asset('manifest.json') }}">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="{{ asset('images/icons/mstile-150x150.png') }}">
    <meta name="theme-color" content="#ffffff">

    <title>Comparti2</title>
    @laravelPWA
{{--    <link href="{{ asset('css/estilos-2.css') }}" rel="stylesheet">--}}
    <!-- Bootstrap core CSS -->
    <link href="{{ asset('vendor/bootstrap/css/bootstrap.min.css') }}" rel="stylesheet">

    <!-- Custom fonts for this template -->
    <link href="{{ asset('vendor/fontawesome-free/css/all.min.css') }}" rel="stylesheet">
    <link href="{{ asset('vendor/simple-line-icons/css/simple-line-icons.css') }}" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">


    <!-- Custom styles for this template -->
    <link href="{{ asset('css/landing-page.min.css') }}" rel="stylesheet">

    @yield('style')
    @toastr_css
    <style type="text/css">

        .searchbar{
            margin-bottom: auto;
            margin-top: auto;
            height: 60px;
            background-color: #f8f9fa;
            border-radius: 30px;
            padding: 10px;
        }

        .search_input{
            color: black;
            border: 0;
            outline: 0;
            background: none;
            width: 0;
            caret-color:black;
            line-height: 40px;
            transition: width 0.4s linear;
        }

        .searchbar:hover > .search_input{
            padding: 0 10px;
            width: 750px;
            caret-color:white;
            transition: width 0.4s linear;
        }



        .search_icon{
            height: 40px;
            width: 40px;
            float: right;
            display: flex;
            justify-content: center;
            align-items: center;
            border-radius: 50%;
            color:#5cd169;
            text-decoration:none;
        }



        .bordes {
            border-top-right-radius: 40px !important;
            border-bottom-right-radius: 40px !important;
            border-top-left-radius: 40px !important;
            border-bottom-left-radius: 40px !important;
        }

        .borderder{
            border-top-right-radius: 20px !important;
            border-bottom-right-radius: 20px !important;
        }

        .borderiz{
            border-top-left-radius: 20px !important;
            border-bottom-left-radius: 20px !important;
        }

        .box{
            width: 100%;
            height: 100%;
        }

        .espacios{
            padding: 0px !important;
        }


        #container2 {
            width: auto;
            height: auto;
            overflow: hidden;
            padding-bottom: 20px;
        }
        #modules::-webkit-scrollbar {
            height: 5px;
            /*background: #303030;*/
            background: white;
        }


        #modules::-webkit-scrollbar:hover {
            height: 5px;
            background: #5cd169;
        }

        #modules {
            height:auto;
            white-space:nowrap;
            overflow-x: scroll;
            overflow-y: hide;
            -webkit-overflow-scrolling:touch;

            &::-webkit-scrollbar {
                 display: none;
            }


        }

        .module {
            display:inline-block;
            width:auto;
            height:auto;
            line-height:auto;
            text-align:center;
        }
        .module + .module {
            margin-left:5px
        }


        @media (min-width: 360px) {
            .2{
                padding: 0px;

            }

            /*.searchbar:hover > .search_input{*/
            /*    width: 50%;*/
            /*}*/
        }

        @media (max-width: 760px) {
            .searchbar:hover > .search_input{
                width: 50%;
            }

        }

    </style>

</head>

<body>
    @include('layouts.frontend.header')
        @yield('content')
    @include('layouts.frontend.footer')

    <!-- Bootstrap - JavaScript -->
    <script src="{{ asset('vendor/jquery/jquery.min.js') }}"></script>
    <script src="{{ asset('vendor/bootstrap/js/bootstrap.bundle.min.js') }}"></script>


    <form id="logoutform" action="{{ route('logout') }}" method="POST" style="display: none;">
        {{ csrf_field() }}
    </form>

    <script>
        $(function() {
            toastr.options.closeButton = true;
            toastr.options.closeMethod = 'fadeOut';
            toastr.options.closeDuration = 200;
        });
    </script>
    @yield('scripts')
    @toastr_js
    @toastr_render
</body>
</html>